In [1]:
import pandas as pd
import re

In [2]:
df = pd.read_csv("../data/amazon_reviews_20000.csv")

print("Dataset shape:", df.shape)
df.head()

Dataset shape: (20000, 3)

                                         review_text  label sentiment
0  Good diapers, some blowouts I like these diape...      1      GOOD
1  Broke within a month Even though I always peel...      0       BAD
2  Manipulative, offensive, innacurate As others ...      0       BAD
3  The Truman Show for Dummies A watered-down Tru...      0       BAD
4  Straight Fire! Holy Culture was my introductio...      1      GOOD

In [3]:
for i, review in enumerate(df["review_text"].head(5), start=1):
    print(f"\nReview {i}:")
    print(review)

Review 1:
Good diapers, some blowouts I like these diapers and it's great to get so many at once, but we have had some blowouts up the back.

Review 2:
Broke within a month Even though I always peeled the cloves, this press didn't do a good job fully pressing the garlic. And then, after only a few weeks, it snapped in two as I was pressing a clove - avoid this one!

Review 3:
Manipulative, offensive, innacurate As others said, the author really botched it with the main character: to imagine that any able-minded German 9-year-old, and a son of a high ranking SS commander to boot, would not have heard of Jews (and hated them) and would not know who the Fuhrer was, or how to pronounce it, is completely preposterous.Furthermore, I found it offensive that the plot went as far as to suggest that two boys could have frequent conversations for almost a year along the unguarded fence. The Jewish boy would have been sent to the gas chamber upon arrival.The result is a "Holocaust-lite" book that I find extremely objectionable.

Review 4:
The Truman Show for Dummies A watered-down Truman Show for people who couldn't understand or don't want to deal with the larger concepts in The Truman Show.

Review 5:
Straight Fire! Holy Culture was my introduction to Cross Movement and since hearing it, I have purchased every CD they released including the solo projects and their old albulms. I have to be honest in saying that I wasn't a big fan of Phanatik until I got this CD. What can I say, this is the hottest Christian Hip Hop CD I have ever heard. The beats, the ryhmes and the production are all of the highest quality. It forced me to go back and listen to some of Phanatik's other songs. After doing so, I would have to say that as a lyricist Phanatik is in my top five all-time of any hip hop genre. This CD is a must have for any fan of real hip hop.

- Convert text to lowercase.
- Remove HTML tags.
- Remove URLs.
- Remove unnecessary punctuation while retaining letters and numbers.
- Normalize repeated whitespace.

In [4]:
def preprocess_text(text):
    text = str(text).lower()

    text = re.sub(r"<[^>]+>", " ", text)
    text = re.sub(r"https?://\S+|www\.\S+", " ", text)

    text = re.sub(r"[^a-z0-9\s']", " ", text)
    text = re.sub(r"\s+", " ", text).strip()

    return text

In [5]:
examples = [
    "THIS PRODUCT IS AMAZING!!!",
    "The product is NOT good.",
    "Works perfectly :) Visit https://example.com"
]

for example in examples:
    print("Original :", example)
    print("Processed:", preprocess_text(example))
    print("-" * 50)

Original : THIS PRODUCT IS AMAZING!!!
Processed: this product is amazing
--------------------------------------------------
Original : The product is NOT good.
Processed: the product is not good
--------------------------------------------------
Original : Works perfectly :) Visit https://example.com
Processed: works perfectly visit
--------------------------------------------------

In [6]:
df["cleaned_text"] = df["review_text"].apply(preprocess_text)

df[["review_text", "cleaned_text", "sentiment"]].head(10)

,review_text,cleaned_text,sentiment
0,"Good diapers, some blowouts I like these diape...",good diapers some blowouts i like these diaper...,GOOD
1,Broke within a month Even though I always peel...,broke within a month even though i always peel...,BAD
2,"Manipulative, offensive, innacurate As others ...",manipulative offensive innacurate as others sa...,BAD
3,The Truman Show for Dummies A watered-down Tru...,the truman show for dummies a watered down tru...,BAD
4,Straight Fire! Holy Culture was my introductio...,straight fire holy culture was my introduction...,GOOD
5,Kids Love SB It's a fun movie that involves Sp...,kids love sb it's a fun movie that involves sp...,GOOD
6,A unique collection of stories This was a fun ...,a unique collection of stories this was a fun ...,GOOD
7,so-so my 3- and 4- yr olds liked this globe qu...,so so my 3 and 4 yr olds liked this globe quit...,BAD
8,Modern Scrooge Waited a long time for this ver...,modern scrooge waited a long time for this ver...,GOOD
9,Baldacci should've gotten life for this manure...,baldacci should've gotten life for this manure...,BAD

In [7]:
empty_reviews = df["cleaned_text"].str.strip().eq("").sum()

print("Empty reviews after preprocessing:", empty_reviews)

Empty reviews after preprocessing: 0

In [8]:
print(
    "Duplicate cleaned reviews:",
    df["cleaned_text"].duplicated().sum()
)

Duplicate cleaned reviews: 0

In [10]:
path="../data/amazon_reviews_preprocessed.csv"
df.to_csv(
    path,
    index=False,
    encoding="utf-8"
)

print("Preprocessed dataset saved.")
print("Shape:", df.shape)

Preprocessed dataset saved.
Shape: (20000, 4)

In [11]:
print("Missing cleaned text:", df["cleaned_text"].isna().sum())
print("Empty cleaned text:", df["cleaned_text"].str.strip().eq("").sum())

print("\nClass distribution:")
print(df["sentiment"].value_counts())

df.sample(5, random_state=42)[
    ["review_text", "cleaned_text", "sentiment"]
]

Missing cleaned text: 0
Empty cleaned text: 0

Class distribution:
sentiment
GOOD    10000
BAD     10000
Name: count, dtype: int64

,review_text,cleaned_text,sentiment
10650,Disappointing I bought this book because I am ...,disappointing i bought this book because i am ...,BAD
2041,Here's the thing. This Sunflower/ Surf's Up se...,here's the thing this sunflower surf's up set ...,GOOD
8668,Ineffective for promoting vivid dreams I bough...,ineffective for promoting vivid dreams i bough...,BAD
1114,"It's not just about a sheep, people! This book...",it's not just about a sheep people this book t...,GOOD
13902,Excellent helper for new parents This book wen...,excellent helper for new parents this book wen...,GOOD